pipeline {
    agent any
    stages {
        stage('Build Application'){
            steps{
                sh 'mvn clean package'
            }
            post {
                success {
                    echo "Archiving Artifacts"
                    archiveArtifacts artifacts : '**/*.war'
                }
            }
        }
    }
}