pipeline {
    agent any
    tools {
        maven 'LocalMaven'
        jdk 'jdk8'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Archiving Artifact... !"
                    archiveArtifacts artifacts : '**/*.war'
                }
            }
        }
        stage ('Deploying Production') {
            build job : 'Deploying_to_prod'
        }
    }
}